name: CD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -aPvz ./backend/build/ www-data@${{ secrets.SSH_HOST }}:/var/www/hie-server/${GITHUB_REF_NAME}/
